package wx.dao.model;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table p_product
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.product_category_id
     *
     * @mbg.generated
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.delivery_template_id
     *
     * @mbg.generated
     */
    private Long deliveryTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.product_category_name
     *
     * @mbg.generated
     */
    private String productCategoryName;

    /**
     * Database Column Remarks:
     *   产品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     * Database Column Remarks:
     *   货号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.product_sn
     *
     * @mbg.generated
     */
    private String productSn;

    /**
     * Database Column Remarks:
     *   上架状态：0->下架；1->上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.publish_status
     *
     * @mbg.generated
     */
    private Integer publishStatus;

    /**
     * Database Column Remarks:
     *   新品状态:0->不是新品；1->新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.new_status
     *
     * @mbg.generated
     */
    private Integer newStatus;

    /**
     * Database Column Remarks:
     *   推荐状态；0->不推荐；1->推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.recommand_status
     *
     * @mbg.generated
     */
    private Integer recommandStatus;

    /**
     * Database Column Remarks:
     *   审核状态：0->未审核；1->审核通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.verify_status
     *
     * @mbg.generated
     */
    private Integer verifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.sale
     *
     * @mbg.generated
     */
    private Integer sale;

    /**
     * Database Column Remarks:
     *   赠送的成长值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.gift_growth
     *
     * @mbg.generated
     */
    private Integer giftGrowth;

    /**
     * Database Column Remarks:
     *   赠送的积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.gift_point
     *
     * @mbg.generated
     */
    private Integer giftPoint;

    /**
     * Database Column Remarks:
     *   限制使用的积分数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.use_point_limit
     *
     * @mbg.generated
     */
    private Integer usePointLimit;

    /**
     * Database Column Remarks:
     *   副标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.sub_title
     *
     * @mbg.generated
     */
    private String subTitle;

    /**
     * Database Column Remarks:
     *   市场价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.original_price
     *
     * @mbg.generated
     */
    private BigDecimal originalPrice;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   库存预警值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.low_stock
     *
     * @mbg.generated
     */
    private Integer lowStock;

    /**
     * Database Column Remarks:
     *   单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   商品重量，默认为克
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     * Database Column Remarks:
     *   是否为预告商品：0->不是；1->是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.preview_status
     *
     * @mbg.generated
     */
    private Integer previewStatus;

    /**
     * Database Column Remarks:
     *   以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.service_ids
     *
     * @mbg.generated
     */
    private String serviceIds;

    /**
     * Database Column Remarks:
     *   商品关键字,以逗号分隔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * Database Column Remarks:
     *   画册图片，连产品图片限制为5张，以逗号分割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.album_pics
     *
     * @mbg.generated
     */
    private String albumPics;

    /**
     * Database Column Remarks:
     *   详情标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.detail_title
     *
     * @mbg.generated
     */
    private String detailTitle;

    /**
     * Database Column Remarks:
     *   品牌名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   删除时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   详情描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.detail_desc
     *
     * @mbg.generated
     */
    private String detailDesc;

    /**
     * Database Column Remarks:
     *   产品详情网页内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.detail_html
     *
     * @mbg.generated
     */
    private String detailHtml;

    /**
     * Database Column Remarks:
     *   移动端网页详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.detail_mobile_html
     *
     * @mbg.generated
     */
    private String detailMobileHtml;
}