@startuml
title __**定时统计租户工单数目信息**__

autonumber

control 浏览器 AS  B #red
entity 应用服务器 AS  S #green
entity 消息队列 AS  MQ #0088EE
database 数据库  AS DB


== 1、服务器定时任务 ==

S->DB: 查询到所有有效的租户IDS
return 所有的有效租户信息

group 遍历数据IDS发送到MQ
S->MQ: 单个发送消息到消息队列
end

== 2、异步处理消息 ==

group 异步处理消息
MQ->S: 服务端j接收到到消息
S->DB: 查询租户的信息
return 返回租户的工单数据

S->DB: 处理好的数据，持久化到SUMMARY表

S-->MQ: [Auto] 发送ACK，确认消息被消费

end


== 3、用户查询数据 ==

B->S: 给定查询天数,查询统计信息
S->DB: 查询数据中创建时间最大的数据返回
return 返回统计好的数据
S->B: 返回数据给前端

@enduml