package wx.repository.wsat.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComponentDaoExample {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public ComponentDaoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("_id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("_id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Integer value) {
      addCriterion("_id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Integer value) {
      addCriterion("_id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Integer value) {
      addCriterion("_id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("_id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Integer value) {
      addCriterion("_id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Integer value) {
      addCriterion("_id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Integer> values) {
      addCriterion("_id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Integer> values) {
      addCriterion("_id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Integer value1, Integer value2) {
      addCriterion("_id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Integer value1, Integer value2) {
      addCriterion("_id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCIdIsNull() {
      addCriterion("c_id is null");
      return (Criteria) this;
    }

    public Criteria andCIdIsNotNull() {
      addCriterion("c_id is not null");
      return (Criteria) this;
    }

    public Criteria andCIdEqualTo(String value) {
      addCriterion("c_id =", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdNotEqualTo(String value) {
      addCriterion("c_id <>", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdGreaterThan(String value) {
      addCriterion("c_id >", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdGreaterThanOrEqualTo(String value) {
      addCriterion("c_id >=", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdLessThan(String value) {
      addCriterion("c_id <", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdLessThanOrEqualTo(String value) {
      addCriterion("c_id <=", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdLike(String value) {
      addCriterion("c_id like", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdNotLike(String value) {
      addCriterion("c_id not like", value, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdIn(List<String> values) {
      addCriterion("c_id in", values, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdNotIn(List<String> values) {
      addCriterion("c_id not in", values, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdBetween(String value1, String value2) {
      addCriterion("c_id between", value1, value2, "cId");
      return (Criteria) this;
    }

    public Criteria andCIdNotBetween(String value1, String value2) {
      addCriterion("c_id not between", value1, value2, "cId");
      return (Criteria) this;
    }

    public Criteria andCNameIsNull() {
      addCriterion("c_name is null");
      return (Criteria) this;
    }

    public Criteria andCNameIsNotNull() {
      addCriterion("c_name is not null");
      return (Criteria) this;
    }

    public Criteria andCNameEqualTo(String value) {
      addCriterion("c_name =", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameNotEqualTo(String value) {
      addCriterion("c_name <>", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameGreaterThan(String value) {
      addCriterion("c_name >", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameGreaterThanOrEqualTo(String value) {
      addCriterion("c_name >=", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameLessThan(String value) {
      addCriterion("c_name <", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameLessThanOrEqualTo(String value) {
      addCriterion("c_name <=", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameLike(String value) {
      addCriterion("c_name like", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameNotLike(String value) {
      addCriterion("c_name not like", value, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameIn(List<String> values) {
      addCriterion("c_name in", values, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameNotIn(List<String> values) {
      addCriterion("c_name not in", values, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameBetween(String value1, String value2) {
      addCriterion("c_name between", value1, value2, "cName");
      return (Criteria) this;
    }

    public Criteria andCNameNotBetween(String value1, String value2) {
      addCriterion("c_name not between", value1, value2, "cName");
      return (Criteria) this;
    }

    public Criteria andCFirstIsNull() {
      addCriterion("c_first is null");
      return (Criteria) this;
    }

    public Criteria andCFirstIsNotNull() {
      addCriterion("c_first is not null");
      return (Criteria) this;
    }

    public Criteria andCFirstEqualTo(String value) {
      addCriterion("c_first =", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstNotEqualTo(String value) {
      addCriterion("c_first <>", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstGreaterThan(String value) {
      addCriterion("c_first >", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstGreaterThanOrEqualTo(String value) {
      addCriterion("c_first >=", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstLessThan(String value) {
      addCriterion("c_first <", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstLessThanOrEqualTo(String value) {
      addCriterion("c_first <=", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstLike(String value) {
      addCriterion("c_first like", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstNotLike(String value) {
      addCriterion("c_first not like", value, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstIn(List<String> values) {
      addCriterion("c_first in", values, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstNotIn(List<String> values) {
      addCriterion("c_first not in", values, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstBetween(String value1, String value2) {
      addCriterion("c_first between", value1, value2, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCFirstNotBetween(String value1, String value2) {
      addCriterion("c_first not between", value1, value2, "cFirst");
      return (Criteria) this;
    }

    public Criteria andCTypeIsNull() {
      addCriterion("c_type is null");
      return (Criteria) this;
    }

    public Criteria andCTypeIsNotNull() {
      addCriterion("c_type is not null");
      return (Criteria) this;
    }

    public Criteria andCTypeEqualTo(String value) {
      addCriterion("c_type =", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeNotEqualTo(String value) {
      addCriterion("c_type <>", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeGreaterThan(String value) {
      addCriterion("c_type >", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeGreaterThanOrEqualTo(String value) {
      addCriterion("c_type >=", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeLessThan(String value) {
      addCriterion("c_type <", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeLessThanOrEqualTo(String value) {
      addCriterion("c_type <=", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeLike(String value) {
      addCriterion("c_type like", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeNotLike(String value) {
      addCriterion("c_type not like", value, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeIn(List<String> values) {
      addCriterion("c_type in", values, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeNotIn(List<String> values) {
      addCriterion("c_type not in", values, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeBetween(String value1, String value2) {
      addCriterion("c_type between", value1, value2, "cType");
      return (Criteria) this;
    }

    public Criteria andCTypeNotBetween(String value1, String value2) {
      addCriterion("c_type not between", value1, value2, "cType");
      return (Criteria) this;
    }

    public Criteria andProducerIsNull() {
      addCriterion("producer is null");
      return (Criteria) this;
    }

    public Criteria andProducerIsNotNull() {
      addCriterion("producer is not null");
      return (Criteria) this;
    }

    public Criteria andProducerEqualTo(String value) {
      addCriterion("producer =", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerNotEqualTo(String value) {
      addCriterion("producer <>", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerGreaterThan(String value) {
      addCriterion("producer >", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerGreaterThanOrEqualTo(String value) {
      addCriterion("producer >=", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerLessThan(String value) {
      addCriterion("producer <", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerLessThanOrEqualTo(String value) {
      addCriterion("producer <=", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerLike(String value) {
      addCriterion("producer like", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerNotLike(String value) {
      addCriterion("producer not like", value, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerIn(List<String> values) {
      addCriterion("producer in", values, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerNotIn(List<String> values) {
      addCriterion("producer not in", values, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerBetween(String value1, String value2) {
      addCriterion("producer between", value1, value2, "producer");
      return (Criteria) this;
    }

    public Criteria andProducerNotBetween(String value1, String value2) {
      addCriterion("producer not between", value1, value2, "producer");
      return (Criteria) this;
    }

    public Criteria andCreatedAtIsNull() {
      addCriterion("created_at is null");
      return (Criteria) this;
    }

    public Criteria andCreatedAtIsNotNull() {
      addCriterion("created_at is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedAtEqualTo(Date value) {
      addCriterion("created_at =", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtNotEqualTo(Date value) {
      addCriterion("created_at <>", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtGreaterThan(Date value) {
      addCriterion("created_at >", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
      addCriterion("created_at >=", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtLessThan(Date value) {
      addCriterion("created_at <", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
      addCriterion("created_at <=", value, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtIn(List<Date> values) {
      addCriterion("created_at in", values, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtNotIn(List<Date> values) {
      addCriterion("created_at not in", values, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtBetween(Date value1, Date value2) {
      addCriterion("created_at between", value1, value2, "createdAt");
      return (Criteria) this;
    }

    public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
      addCriterion("created_at not between", value1, value2, "createdAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtIsNull() {
      addCriterion("updated_at is null");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtIsNotNull() {
      addCriterion("updated_at is not null");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtEqualTo(Date value) {
      addCriterion("updated_at =", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtNotEqualTo(Date value) {
      addCriterion("updated_at <>", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtGreaterThan(Date value) {
      addCriterion("updated_at >", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
      addCriterion("updated_at >=", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtLessThan(Date value) {
      addCriterion("updated_at <", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
      addCriterion("updated_at <=", value, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtIn(List<Date> values) {
      addCriterion("updated_at in", values, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtNotIn(List<Date> values) {
      addCriterion("updated_at not in", values, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtBetween(Date value1, Date value2) {
      addCriterion("updated_at between", value1, value2, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
      addCriterion("updated_at not between", value1, value2, "updatedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtIsNull() {
      addCriterion("deleted_at is null");
      return (Criteria) this;
    }

    public Criteria andDeletedAtIsNotNull() {
      addCriterion("deleted_at is not null");
      return (Criteria) this;
    }

    public Criteria andDeletedAtEqualTo(Date value) {
      addCriterion("deleted_at =", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtNotEqualTo(Date value) {
      addCriterion("deleted_at <>", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtGreaterThan(Date value) {
      addCriterion("deleted_at >", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtGreaterThanOrEqualTo(Date value) {
      addCriterion("deleted_at >=", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtLessThan(Date value) {
      addCriterion("deleted_at <", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtLessThanOrEqualTo(Date value) {
      addCriterion("deleted_at <=", value, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtIn(List<Date> values) {
      addCriterion("deleted_at in", values, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtNotIn(List<Date> values) {
      addCriterion("deleted_at not in", values, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtBetween(Date value1, Date value2) {
      addCriterion("deleted_at between", value1, value2, "deletedAt");
      return (Criteria) this;
    }

    public Criteria andDeletedAtNotBetween(Date value1, Date value2) {
      addCriterion("deleted_at not between", value1, value2, "deletedAt");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * component
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
