package wx.repository.wsat.dao.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table
 * component
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class ComponentDaoWithBLOBs extends ComponentDao {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.desc
   *
   * @mbg.generated
   */
  private String desc;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.properties
   *
   * @mbg.generated
   */
  private String properties;
}
