package wx.repository.wsat.dao.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table
 * component
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ComponentDao {
  /**
   * Database Column Remarks: _ID，内部自增编号
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * component._id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * Database Column Remarks: 组件编号
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.c_id
   *
   * @mbg.generated
   */
  private String cId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.c_name
   *
   * @mbg.generated
   */
  private String cName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.c_first
   *
   * @mbg.generated
   */
  private String cFirst;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.c_type
   *
   * @mbg.generated
   */
  private String cType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.producer
   *
   * @mbg.generated
   */
  private String producer;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.created_at
   *
   * @mbg.generated
   */
  private Date createdAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.updated_at
   *
   * @mbg.generated
   */
  private Date updatedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * component.deleted_at
   *
   * @mbg.generated
   */
  private Date deletedAt;
}
