package wx.repository.wsat.dao.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table poc
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PocDao {
  /**
   * Database Column Remarks: _ID，内部自增编号
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc._id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.poc_id
   *
   * @mbg.generated
   */
  private String pocId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.vuln_id
   *
   * @mbg.generated
   */
  private String vulnId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.poc_name
   *
   * @mbg.generated
   */
  private String pocName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.author
   *
   * @mbg.generated
   */
  private String author;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.create_time
   *
   * @mbg.generated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.image_name
   *
   * @mbg.generated
   */
  private String imageName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.created_at
   *
   * @mbg.generated
   */
  private Date createdAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.updated_at
   *
   * @mbg.generated
   */
  private Date updatedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.deleted_at
   *
   * @mbg.generated
   */
  private Date deletedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * poc.args
   *
   * @mbg.generated
   */
  private String args;
}
