package wx.repository.wsat.dao.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table
 * strategy
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StrategyDaoKey {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy._id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.created_at
   *
   * @mbg.generated
   */
  private Date createdAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.create_time
   *
   * @mbg.generated
   */
  private Date createTime;
}
