package wx.repository.wsat.dao.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table
 * strategy
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class StrategyDao extends StrategyDaoKey {
  /**
   * Database Column Remarks: 策略 ID
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.strategy_id
   *
   * @mbg.generated
   */
  private String strategyId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.strategy_name
   *
   * @mbg.generated
   */
  private String strategyName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.author
   *
   * @mbg.generated
   */
  private String author;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.image_name
   *
   * @mbg.generated
   */
  private String imageName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.updated_at
   *
   * @mbg.generated
   */
  private Date updatedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.deleted_at
   *
   * @mbg.generated
   */
  private Date deletedAt;

  /**
   * Database Column Remarks: 策略描述
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * strategy.desc
   *
   * @mbg.generated
   */
  private String desc;
}
