package wx.repository.wsat.dao.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table vuln
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VulnDao {
  /**
   * Database Column Remarks: _ID，内部自增编号
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln._id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.vuln_id
   *
   * @mbg.generated
   */
  private String vulnId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.vuln_name
   *
   * @mbg.generated
   */
  private String vulnName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.vuln_type
   *
   * @mbg.generated
   */
  private Integer vulnType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.c_id
   *
   * @mbg.generated
   */
  private String cId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.c_version
   *
   * @mbg.generated
   */
  private String cVersion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.cnvd_id
   *
   * @mbg.generated
   */
  private String cnvdId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.cve_id
   *
   * @mbg.generated
   */
  private String cveId;

  /**
   * Database Column Remarks: 披露时间
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.disclosure_date
   *
   * @mbg.generated
   */
  private Date disclosureDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.submit_time
   *
   * @mbg.generated
   */
  private Date submitTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.level
   *
   * @mbg.generated
   */
  private Integer level;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.created_at
   *
   * @mbg.generated
   */
  private Date createdAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.updated_at
   *
   * @mbg.generated
   */
  private Date updatedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.deleted_at
   *
   * @mbg.generated
   */
  private Date deletedAt;
}
