package wx.repository.wsat.dao.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table vuln
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class VulnDaoWithBLOBs extends VulnDao {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.source
   *
   * @mbg.generated
   */
  private String source;

  /**
   * Database Column Remarks: 漏洞介绍
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.detail
   *
   * @mbg.generated
   */
  private String detail;

  /**
   * Database Column Remarks: 漏洞发现/利用详情 HTML
   *
   * <p>This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.exploit
   *
   * @mbg.generated
   */
  private String exploit;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vuln.analysis
   *
   * @mbg.generated
   */
  private String analysis;
}
