package wx.repository.wsat.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import wx.repository.wsat.dao.model.ComponentDao;
import wx.repository.wsat.dao.model.ComponentDaoExample;
import wx.repository.wsat.dao.model.ComponentDaoWithBLOBs;

@Mapper
@Component
public interface ComponentDaoMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  long countByExample(ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int deleteByExample(ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int insert(ComponentDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int insertSelective(ComponentDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  List<ComponentDaoWithBLOBs> selectByExampleWithBLOBs(ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  List<ComponentDao> selectByExample(ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  ComponentDaoWithBLOBs selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByExampleSelective(
      @Param("record") ComponentDaoWithBLOBs record, @Param("example") ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByExampleWithBLOBs(
      @Param("record") ComponentDaoWithBLOBs record, @Param("example") ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByExample(
      @Param("record") ComponentDao record, @Param("example") ComponentDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(ComponentDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(ComponentDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * component
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(ComponentDao record);
}
