package wx.repository.wsat.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import wx.repository.wsat.dao.model.PocDao;
import wx.repository.wsat.dao.model.PocDaoExample;

@Mapper
@Component
public interface PocDaoMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  long countByExample(PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int deleteByExample(PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int insert(PocDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int insertSelective(PocDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  List<PocDao> selectByExampleWithBLOBs(PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  List<PocDao> selectByExample(PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  PocDao selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByExampleSelective(
      @Param("record") PocDao record, @Param("example") PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByExampleWithBLOBs(
      @Param("record") PocDao record, @Param("example") PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByExample(@Param("record") PocDao record, @Param("example") PocDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(PocDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(PocDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * poc
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(PocDao record);
}
