package wx.repository.wsat.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import wx.repository.wsat.dao.model.StrategyDao;
import wx.repository.wsat.dao.model.StrategyDaoExample;
import wx.repository.wsat.dao.model.StrategyDaoKey;

@Mapper
@Component
public interface StrategyDaoMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  long countByExample(StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int deleteByExample(StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(StrategyDaoKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int insert(StrategyDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int insertSelective(StrategyDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  List<StrategyDao> selectByExampleWithBLOBs(StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  List<StrategyDao> selectByExample(StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  StrategyDao selectByPrimaryKey(StrategyDaoKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByExampleSelective(
      @Param("record") StrategyDao record, @Param("example") StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByExampleWithBLOBs(
      @Param("record") StrategyDao record, @Param("example") StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByExample(
      @Param("record") StrategyDao record, @Param("example") StrategyDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(StrategyDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(StrategyDao record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * strategy
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(StrategyDao record);
}
