package wx.repository.wsat.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import wx.repository.wsat.dao.model.VulnDao;
import wx.repository.wsat.dao.model.VulnDaoExample;
import wx.repository.wsat.dao.model.VulnDaoWithBLOBs;

@Mapper
@Component
public interface VulnDaoMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  long countByExample(VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int deleteByExample(VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int insert(VulnDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int insertSelective(VulnDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  List<VulnDaoWithBLOBs> selectByExampleWithBLOBs(VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  List<VulnDao> selectByExample(VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  VulnDaoWithBLOBs selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByExampleSelective(
      @Param("record") VulnDaoWithBLOBs record, @Param("example") VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByExampleWithBLOBs(
      @Param("record") VulnDaoWithBLOBs record, @Param("example") VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByExample(@Param("record") VulnDao record, @Param("example") VulnDaoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(VulnDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(VulnDaoWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * vuln
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(VulnDao record);
}
