server.port: 8080

spring.zipkin.baseUrl: http://localhost:9411/

customers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

addresses:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

spring:
  output:
    ansi:
      enabled: always
