spring:
  profiles:
    active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

server:
  host: 0.0.0.0

mybatis:
  mapper-locations:
  - classpath:com/cy/wsat/agent/repository/dao/xml/*.xml

security:
  jwt:
    authority-claim: authorities
    token-header: Authorization
    token-prefix: 'Bearer '
    expiration-ms: 86400000
    secret: wsat-agent-secret
  public-urls:
    POST:
    - /login